#!/usr/bin/env python3
"""
field_access_report.py

Reads Data Sensitivity Level and Compliance Categorization metadata for a
list of fields via the Salesforce Tooling API, and writes a Markdown table
you can paste into docs/field-access-worksheet.md.

READ-ONLY. This script only issues SOQL queries against the Tooling API's
FieldDefinition object. It does not write, deploy, or modify anything in
your org. It requires the Salesforce CLI (`sf`) to already be authenticated
against a target org you choose explicitly with --target-org.

WHY THIS EXISTS / WHAT IT CANNOT DO (read this before you trust the output):
Salesforce exposes Data Sensitivity Level (FieldDefinition.SecurityClassification)
and Compliance Categorization (FieldDefinition.ComplianceGroup) via the Tooling
API - see https://help.salesforce.com/s/articleView?id=platform.data_classification_metadata_fields.htm
- but only if someone in your org actually populated those values in Setup.
Most orgs have not classified every field. This script will return blank
values for unclassified fields; it is not a substitute for a human deciding
what's actually sensitive. It also does not know which fields your agent's
permission set can access - it only reports classification metadata for the
object/field list you give it. Cross-reference its output against your
permission set by hand.

USAGE:
    sf org login web --alias my-govcloud-org
    python3 scripts/field_access_report.py \
        --target-org my-govcloud-org \
        --object Case --object Contact \
        --output field-access-report.md

Requires: Salesforce CLI (`sf`) installed and authenticated. Python 3.8+.
No third-party Python packages required (uses only the standard library).
"""

import argparse
import json
import subprocess
import sys
from datetime import date


TOOLING_QUERY_TEMPLATE = (
    "SELECT QualifiedApiName, SecurityClassification, ComplianceGroup "
    "FROM FieldDefinition "
    "WHERE EntityDefinition.QualifiedApiName = '{object_name}'"
)


def run_tooling_query(target_org: str, soql: str) -> dict:
    """Run a Tooling API SOQL query via the sf CLI and return parsed JSON.

    Uses `sf data query --use-tooling-api` which is read-only against the org.
    """
    cmd = [
        "sf", "data", "query",
        "--query", soql,
        "--target-org", target_org,
        "--use-tooling-api",
        "--json",
    ]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
    except FileNotFoundError:
        print(
            "ERROR: `sf` CLI not found. Install the Salesforce CLI first: "
            "https://developer.salesforce.com/tools/salesforcecli",
            file=sys.stderr,
        )
        sys.exit(1)
    except subprocess.CalledProcessError as e:
        print(f"ERROR running sf CLI query: {e.stderr}", file=sys.stderr)
        sys.exit(1)

    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError:
        print(f"ERROR: could not parse sf CLI output as JSON:\n{result.stdout}", file=sys.stderr)
        sys.exit(1)


def build_rows(target_org: str, objects: list[str]) -> list[dict]:
    rows = []
    for obj in objects:
        soql = TOOLING_QUERY_TEMPLATE.format(object_name=obj)
        payload = run_tooling_query(target_org, soql)
        records = payload.get("result", {}).get("records", [])
        if not records:
            rows.append({
                "field": f"{obj}.*",
                "sensitivity": "(no fields returned - check object name or field permissions)",
                "compliance": "",
            })
            continue
        for rec in records:
            field_name = f"{obj}.{rec.get('QualifiedApiName', '?')}"
            sensitivity = rec.get("SecurityClassification") or "(not classified in this org)"
            compliance = rec.get("ComplianceGroup") or "-"
            rows.append({
                "field": field_name,
                "sensitivity": sensitivity,
                "compliance": compliance,
            })
    return rows


def write_markdown(rows: list[dict], output_path: str, objects: list[str]) -> None:
    today = date.today().isoformat()
    lines = [
        f"# Field Access Report - generated {today}",
        "",
        f"Objects queried: {', '.join(objects)}",
        "",
        "This table was generated by `scripts/field_access_report.py` against a live org's",
        "Tooling API. It reports Data Sensitivity Level and Compliance Categorization metadata",
        "ONLY where your org has populated it. Blank or '(not classified in this org)' rows need",
        "a manual entry - see docs/field-access-worksheet.md.",
        "",
        "This report does NOT tell you which fields your agent's permission set can access.",
        "Cross-reference the Object.Field column against your agent's permission set by hand.",
        "",
        "| Object.Field | Agent access (fill in manually) | Data Sensitivity Level | Compliance Categorization | Source | Reviewed by | Date |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append(
            f"| {row['field']} | *(fill in)* | {row['sensitivity']} | {row['compliance']} "
            f"| Auto (Tooling API) | *(fill in)* | {today} |"
        )
    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {len(rows)} rows to {output_path}")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--target-org", required=True, help="sf CLI target org alias or username")
    parser.add_argument("--object", action="append", dest="objects", required=True,
                         help="API name of an object to report on. Repeat for multiple objects.")
    parser.add_argument("--output", default="field-access-report.md", help="Output Markdown file path")
    args = parser.parse_args()

    rows = build_rows(args.target_org, args.objects)
    write_markdown(rows, args.output, args.objects)


if __name__ == "__main__":
    main()
